### PR TITLE
A new option to avoid listen mousemove events

### PR DESCRIPTION
**Pull request by fpuga**
refs #10 

This is the first approach, how to pass the option to the handler should be documented, and the previous behaviour should be kept by default.

'almostOnMouseMove' is used as the name option in case, the options to the handler must be passed by means of map options to avoid name collision

### CODE REVIEW

**Review by leplatrem — COMMENTED** [review]
It looks good, but it's a breaking change. I would keep the default to `true` to avoid it

**Comment by fpuga** [comment]
Thanks for the review @leplatrem 

I re-wrote the branch (push -f), as i figure out how to pass options to the handler and added some doc and a new test. The previous behaviour is maintained.

**Review by mabhub — APPROVED** [review]

**Comment by leplatrem** [comment]
So you moved `samplingPeriod` to map options. Was it mandatory?
This is a breaking change I guess, it should be released as a major version

**Comment by fpuga** [comment]
It's not mandatory.

AFAIK the only way to pass options to a handler is as map options. I moved al the previous `options` of the handler as possible map options to allow customization. Previously to my PR, they work as constants. If a dev wanted to change them, the plugin must be hacked. In this way can just be be passed as map options.

I'm not sure that this is a breaking change, as the behaviour of the plugin is the same. But if you don't feel comfortable with the PR, i can rewrite it and only put almostOnMouseMove as map options, and keep the others as previously.

Thanks for your review @leplatrem

**Review by leplatrem — APPROVED** [review]
No problem, I just wanted to make sure it was intentional ;)

**Comment by fpuga** [comment]
Thanks for the merge.

Maybe this issue can be closed #10

**Pull request merged**
